import 'server_flag.dart';

class ServerNameUtils {
  static const Map<String, String> _keywords = {
    'россия': 'RU',
    'германия': 'DE',
    'нидерланды': 'NL',
    'эстония': 'EE',
    'финляндия': 'FI',
    'франция': 'FR',
    'польша': 'PL',
    'швеция': 'SE',
    'норвегия': 'NO',
    'дания': 'DK',
    'австрия': 'AT',
    'швейцария': 'CH',
    'бельгия': 'BE',
    'чехия': 'CZ',
    'венгрия': 'HU',
    'румыния': 'RO',
    'болгария': 'BG',
    'греция': 'GR',
    'италия': 'IT',
    'испания': 'ES',
    'португалия': 'PT',
    'великобритания': 'GB',
    'ирландия': 'IE',
    'исландия': 'IS',
    'латвия': 'LV',
    'литва': 'LT',
    'словакия': 'SK',
    'словения': 'SI',
    'хорватия': 'HR',
    'сербия': 'RS',
    'молдова': 'MD',
    'украина': 'UA',
    'беларусь': 'BY',
    'казахстан': 'KZ',
    'турция': 'TR',
    'израиль': 'IL',
    'оаэ': 'AE',
    'индия': 'IN',
    'китай': 'CN',
    'япония': 'JP',
    'корея': 'KR',
    'сингапур': 'SG',
    'гонконг': 'HK',
    'тайвань': 'TW',
    'австралия': 'AU',
    'новая зеландия': 'NZ',
    'канада': 'CA',
    'сша': 'US',
    'бразилия': 'BR',
    'аргентина': 'AR',
    'мексика': 'MX',
    'чили': 'CL',
    'колумбия': 'CO',
    'перу': 'PE',
    'южная африка': 'ZA',
    'нигерия': 'NG',
    'египет': 'EG',
    'таиланд': 'TH',
    'вьетнам': 'VN',
    'индонезия': 'ID',
    'малайзия': 'MY',
    'пакистан': 'PK',
    'иран': 'IR',
    'саудовская аравия': 'SA',
    'катар': 'QA',
    'кувейт': 'KW',
    'russia': 'RU',
    'germany': 'DE',
    'deutsch': 'DE',
    'netherlands': 'NL',
    'holland': 'NL',
    'estonia': 'EE',
    'finland': 'FI',
    'france': 'FR',
    'poland': 'PL',
    'sweden': 'SE',
    'norway': 'NO',
    'denmark': 'DK',
    'austria': 'AT',
    'switzerland': 'CH',
    'swiss': 'CH',
    'belgium': 'BE',
    'czech': 'CZ',
    'czechia': 'CZ',
    'hungary': 'HU',
    'romania': 'RO',
    'bulgaria': 'BG',
    'greece': 'GR',
    'italy': 'IT',
    'spain': 'ES',
    'portugal': 'PT',
    'britain': 'GB',
    'united kingdom': 'GB',
    'england': 'GB',
    'ireland': 'IE',
    'iceland': 'IS',
    'latvia': 'LV',
    'lithuania': 'LT',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'croatia': 'HR',
    'serbia': 'RS',
    'moldova': 'MD',
    'ukraine': 'UA',
    'belarus': 'BY',
    'kazakhstan': 'KZ',
    'turkey': 'TR',
    'turkiye': 'TR',
    'israel': 'IL',
    'uae': 'AE',
    'dubai': 'AE',
    'india': 'IN',
    'china': 'CN',
    'japan': 'JP',
    'korea': 'KR',
    'singapore': 'SG',
    'hong kong': 'HK',
    'hongkong': 'HK',
    'taiwan': 'TW',
    'australia': 'AU',
    'new zealand': 'NZ',
    'canada': 'CA',
    'united states': 'US',
    'usa': 'US',
    'america': 'US',
    'brazil': 'BR',
    'argentina': 'AR',
    'mexico': 'MX',
    'chile': 'CL',
    'colombia': 'CO',
    'peru': 'PE',
    'south africa': 'ZA',
    'nigeria': 'NG',
    'egypt': 'EG',
    'thailand': 'TH',
    'vietnam': 'VN',
    'indonesia': 'ID',
    'malaysia': 'MY',
    'pakistan': 'PK',
    'iran': 'IR',
    'iraq': 'IQ',
    'saudi': 'SA',
    'qatar': 'QA',
    'kuwait': 'KW',
    'ru': 'RU',
    'de': 'DE',
    'nl': 'NL',
    'ee': 'EE',
    'fi': 'FI',
    'fr': 'FR',
    'pl': 'PL',
    'se': 'SE',
    'dk': 'DK',
    'at': 'AT',
    'ch': 'CH',
    'be': 'BE',
    'cz': 'CZ',
    'hu': 'HU',
    'ro': 'RO',
    'bg': 'BG',
    'gr': 'GR',
    'it': 'IT',
    'es': 'ES',
    'pt': 'PT',
    'gb': 'GB',
    'uk': 'GB',
    'ie': 'IE',
    'lv': 'LV',
    'lt': 'LT',
    'sk': 'SK',
    'si': 'SI',
    'hr': 'HR',
    'rs': 'RS',
    'md': 'MD',
    'ua': 'UA',
    'by': 'BY',
    'kz': 'KZ',
    'tr': 'TR',
    'il': 'IL',
    'ae': 'AE',
    'cn': 'CN',
    'jp': 'JP',
    'kr': 'KR',
    'sg': 'SG',
    'hk': 'HK',
    'tw': 'TW',
    'au': 'AU',
    'nz': 'NZ',
    'ca': 'CA',
    'us': 'US',
    'br': 'BR',
    'ar': 'AR',
    'mx': 'MX',
    'cl': 'CL',
    'co': 'CO',
    'pe': 'PE',
    'za': 'ZA',
    'ng': 'NG',
    'eg': 'EG',
    'th': 'TH',
    'vn': 'VN',
    'my': 'MY',
    'pk': 'PK',
    'ir': 'IR',
    'iq': 'IQ',
    'sa': 'SA',
    'qa': 'QA',
    'kw': 'KW',
    'est': 'EE',
    'nld': 'NL',
    'deu': 'DE',
    'rus': 'RU',
    'fra': 'FR',
    'pol': 'PL',
    'swe': 'SE',
    'nor': 'NO',
    'dnk': 'DK',
    'aut': 'AT',
    'che': 'CH',
    'bel': 'BE',
    'cze': 'CZ',
    'hun': 'HU',
    'rou': 'RO',
    'bgr': 'BG',
    'grc': 'GR',
    'ita': 'IT',
    'esp': 'ES',
    'prt': 'PT',
    'gbr': 'GB',
    'irl': 'IE',
    'isl': 'IS',
    'lva': 'LV',
    'ltu': 'LT',
    'svk': 'SK',
    'svn': 'SI',
    'hrv': 'HR',
    'srb': 'RS',
    'mda': 'MD',
    'ukr': 'UA',
    'blr': 'BY',
    'kaz': 'KZ',
    'tur': 'TR',
    'isr': 'IL',
    'are': 'AE',
    'ind': 'IN',
    'chn': 'CN',
    'jpn': 'JP',
    'kor': 'KR',
    'sgp': 'SG',
    'hkg': 'HK',
    'twn': 'TW',
    'aus': 'AU',
    'nzl': 'NZ',
    'can': 'CA',
    'bra': 'BR',
    'arg': 'AR',
    'mex': 'MX',
    'chl': 'CL',
    'col': 'CO',
    'per': 'PE',
    'zaf': 'ZA',
    'nga': 'NG',
    'egy': 'EG',
    'tha': 'TH',
    'vnm': 'VN',
    'idn': 'ID',
    'mys': 'MY',
    'pak': 'PK',
    'irn': 'IR',
    'irq': 'IQ',
    'sau': 'SA',
    'qat': 'QA',
    'kwt': 'KW',
  };

  // В китайских именах пробелы между страной, городом и номером необязательны.
  // Только полные названия, без неоднозначных односимвольных сокращений.
  static const Map<String, String> _chineseKeywords = {
    '中国香港': 'HK',
    '中國香港': 'HK',
    '中国澳门': 'MO',
    '中國澳門': 'MO',
    '中国台湾': 'TW',
    '中國台灣': 'TW',
    '中國臺灣': 'TW',
    '香港': 'HK',
    '澳门': 'MO',
    '澳門': 'MO',
    '台湾': 'TW',
    '台灣': 'TW',
    '臺灣': 'TW',
    '中国': 'CN',
    '中國': 'CN',
    '日本': 'JP',
    '韩国': 'KR',
    '韓國': 'KR',
    '新加坡': 'SG',
    '马来西亚': 'MY',
    '馬來西亞': 'MY',
    '印度尼西亚': 'ID',
    '印度尼西亞': 'ID',
    '印尼': 'ID',
    '印度': 'IN',
    '泰国': 'TH',
    '泰國': 'TH',
    '越南': 'VN',
    '菲律宾': 'PH',
    '菲律賓': 'PH',
    '美国': 'US',
    '美國': 'US',
    '加拿大': 'CA',
    '英国': 'GB',
    '英國': 'GB',
    '爱尔兰': 'IE',
    '愛爾蘭': 'IE',
    '德国': 'DE',
    '德國': 'DE',
    '法国': 'FR',
    '法國': 'FR',
    '荷兰': 'NL',
    '荷蘭': 'NL',
    '俄罗斯': 'RU',
    '俄羅斯': 'RU',
    '澳大利亚': 'AU',
    '澳大利亞': 'AU',
    '澳洲': 'AU',
    '新西兰': 'NZ',
    '新西蘭': 'NZ',
    '紐西蘭': 'NZ',
    '瑞士': 'CH',
    '瑞典': 'SE',
    '挪威': 'NO',
    '丹麦': 'DK',
    '丹麥': 'DK',
    '芬兰': 'FI',
    '芬蘭': 'FI',
    '冰岛': 'IS',
    '冰島': 'IS',
    '意大利': 'IT',
    '義大利': 'IT',
    '西班牙': 'ES',
    '葡萄牙': 'PT',
    '奥地利': 'AT',
    '奧地利': 'AT',
    '比利时': 'BE',
    '比利時': 'BE',
    '波兰': 'PL',
    '波蘭': 'PL',
    '捷克': 'CZ',
    '匈牙利': 'HU',
    '罗马尼亚': 'RO',
    '羅馬尼亞': 'RO',
    '保加利亚': 'BG',
    '保加利亞': 'BG',
    '希腊': 'GR',
    '希臘': 'GR',
    '爱沙尼亚': 'EE',
    '愛沙尼亞': 'EE',
    '拉脱维亚': 'LV',
    '拉脫維亞': 'LV',
    '立陶宛': 'LT',
    '乌克兰': 'UA',
    '烏克蘭': 'UA',
    '白俄罗斯': 'BY',
    '白俄羅斯': 'BY',
    '土耳其': 'TR',
    '以色列': 'IL',
    '阿联酋': 'AE',
    '阿聯酋': 'AE',
    '沙特阿拉伯': 'SA',
    '沙烏地阿拉伯': 'SA',
    '卡塔尔': 'QA',
    '卡達': 'QA',
    '巴基斯坦': 'PK',
    '伊朗': 'IR',
    '伊拉克': 'IQ',
    '巴西': 'BR',
    '阿根廷': 'AR',
    '墨西哥': 'MX',
    '智利': 'CL',
    '哥伦比亚': 'CO',
    '哥倫比亞': 'CO',
    '秘鲁': 'PE',
    '秘魯': 'PE',
    '南非': 'ZA',
    '埃及': 'EG',
    '尼日利亚': 'NG',
    '奈及利亞': 'NG',
  };

  static final _chineseCountryPattern = RegExp(
    (_chineseKeywords.keys.toList()
          ..sort((a, b) => b.length.compareTo(a.length)))
        .map(RegExp.escape)
        .join('|'),
  );
  // Точка внутри токена может быть частью адреса, а не границей страны.
  static final _wordSeparator = RegExp(r'[^\p{L}\p{N}.]+', unicode: true);
  static final _outerDots = RegExp(r'^\.+|\.+$');
  static final _nodeNumber = RegExp(r'\d+$');

  /// Флажок сервера: сначала настоящий флаг-эмодзи из имени (любого вида —
  /// см. [ServerFlag]), и только если его нет — догадка по названию страны.
  static ServerFlag? extractFlag(String displayName) {
    if (displayName.isEmpty) return null;
    final emoji = firstFlagIn(displayName);
    if (emoji != null) return emoji;
    final code = _countryCodeFromKeywords(displayName);
    return code == null ? null : FlagArt(code.toLowerCase());
  }

  /// ISO alpha-2 код региона сервера, если у его флажка такой код есть.
  static String? extractCountryCode(String displayName) =>
      switch (extractFlag(displayName)) {
        FlagArt(:final countryCode) => countryCode,
        _ => null,
      };

  static String? _countryCodeFromKeywords(String displayName) {
    final lower = displayName.toLowerCase();

    final chinese = _chineseCountryPattern.firstMatch(lower);
    if (chinese != null) return _chineseKeywords[chinese.group(0)];

    // Разделяем слова, не склеивая буквы через пунктуацию или цифры.
    // Номер после метки (HK01, Japan2) допустим; CN2 — название сети, не страны.
    final tokens = lower
        .split(_wordSeparator)
        .map((s) => s.replaceAll(_outerDots, ''))
        .where((s) => s.isNotEmpty)
        .toList(growable: false);
    final words = ' ${tokens.join(' ')} ';

    // Полное название надёжнее короткого кода. Составные названия также
    // требуют границ слов: "new zealander" не означает New Zealand.
    for (final entry in _keywords.entries) {
      if (entry.key.contains(' ') && words.contains(' ${entry.key} ')) {
        return entry.value;
      }
    }
    final labels = tokens.map(
      (s) => s == 'cn2' ? s : s.replaceFirst(_nodeNumber, ''),
    );
    for (final tok in labels) {
      if (tok.length <= 3) continue;
      final code = _keywords[tok];
      if (code != null) return code;
    }

    for (final tok in labels) {
      final code = _keywords[tok];
      if (code != null) return code;
    }

    return null;
  }

  static String cleanDisplayName(String displayName) {
    final cleaned = stripFlags(displayName).trim();
    final match = RegExp(r'^[A-Z]{2}\s+(.+)$').firstMatch(cleaned);
    return match != null ? match.group(1)!.trim() : cleaned;
  }

  static String formatForDisplay(String displayName, {int maxLength = 30}) {
    final cleaned = cleanDisplayName(displayName);
    if (cleaned.length <= maxLength) return cleaned;
    return '${cleaned.substring(0, maxLength - 3)}...';
  }
}
