import 'server_flag.dart';

class ServerNameUtils {
  static const Map<String, String> _keywords = {
    'россия': 'RU',
    'германия': 'DE',
    'нидерланды': 'NL',
    'эстония': 'EE',
    'финляндия': 'FI',
    'франция': 'FR',
    'польша': 'PL',
    'швеция': 'SE',
    'норвегия': 'NO',
    'дания': 'DK',
    'австрия': 'AT',
    'швейцария': 'CH',
    'бельгия': 'BE',
    'чехия': 'CZ',
    'венгрия': 'HU',
    'румыния': 'RO',
    'болгария': 'BG',
    'греция': 'GR',
    'италия': 'IT',
    'испания': 'ES',
    'португалия': 'PT',
    'великобритания': 'GB',
    'ирландия': 'IE',
    'исландия': 'IS',
    'латвия': 'LV',
    'литва': 'LT',
    'словакия': 'SK',
    'словения': 'SI',
    'хорватия': 'HR',
    'сербия': 'RS',
    'молдова': 'MD',
    'украина': 'UA',
    'беларусь': 'BY',
    'казахстан': 'KZ',
    'турция': 'TR',
    'израиль': 'IL',
    'оаэ': 'AE',
    'индия': 'IN',
    'китай': 'CN',
    'япония': 'JP',
    'корея': 'KR',
    'сингапур': 'SG',
    'гонконг': 'HK',
    'тайвань': 'TW',
    'австралия': 'AU',
    'новая зеландия': 'NZ',
    'канада': 'CA',
    'сша': 'US',
    'бразилия': 'BR',
    'аргентина': 'AR',
    'мексика': 'MX',
    'чили': 'CL',
    'колумбия': 'CO',
    'перу': 'PE',
    'южная африка': 'ZA',
    'нигерия': 'NG',
    'египет': 'EG',
    'таиланд': 'TH',
    'вьетнам': 'VN',
    'индонезия': 'ID',
    'малайзия': 'MY',
    'пакистан': 'PK',
    'иран': 'IR',
    'саудовская аравия': 'SA',
    'катар': 'QA',
    'кувейт': 'KW',
    'russia': 'RU',
    'germany': 'DE',
    'deutsch': 'DE',
    'netherlands': 'NL',
    'holland': 'NL',
    'estonia': 'EE',
    'finland': 'FI',
    'france': 'FR',
    'poland': 'PL',
    'sweden': 'SE',
    'norway': 'NO',
    'denmark': 'DK',
    'austria': 'AT',
    'switzerland': 'CH',
    'swiss': 'CH',
    'belgium': 'BE',
    'czech': 'CZ',
    'czechia': 'CZ',
    'hungary': 'HU',
    'romania': 'RO',
    'bulgaria': 'BG',
    'greece': 'GR',
    'italy': 'IT',
    'spain': 'ES',
    'portugal': 'PT',
    'britain': 'GB',
    'england': 'GB',
    'ireland': 'IE',
    'iceland': 'IS',
    'latvia': 'LV',
    'lithuania': 'LT',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'croatia': 'HR',
    'serbia': 'RS',
    'moldova': 'MD',
    'ukraine': 'UA',
    'belarus': 'BY',
    'kazakhstan': 'KZ',
    'turkey': 'TR',
    'turkiye': 'TR',
    'israel': 'IL',
    'uae': 'AE',
    'dubai': 'AE',
    'india': 'IN',
    'china': 'CN',
    'japan': 'JP',
    'korea': 'KR',
    'singapore': 'SG',
    'hong kong': 'HK',
    'hongkong': 'HK',
    'taiwan': 'TW',
    'australia': 'AU',
    'new zealand': 'NZ',
    'canada': 'CA',
    'united states': 'US',
    'usa': 'US',
    'america': 'US',
    'brazil': 'BR',
    'argentina': 'AR',
    'mexico': 'MX',
    'chile': 'CL',
    'colombia': 'CO',
    'peru': 'PE',
    'south africa': 'ZA',
    'nigeria': 'NG',
    'egypt': 'EG',
    'thailand': 'TH',
    'vietnam': 'VN',
    'indonesia': 'ID',
    'malaysia': 'MY',
    'pakistan': 'PK',
    'iran': 'IR',
    'iraq': 'IQ',
    'saudi': 'SA',
    'qatar': 'QA',
    'kuwait': 'KW',
    'ru': 'RU',
    'de': 'DE',
    'nl': 'NL',
    'ee': 'EE',
    'fi': 'FI',
    'fr': 'FR',
    'pl': 'PL',
    'se': 'SE',
    'dk': 'DK',
    'at': 'AT',
    'ch': 'CH',
    'be': 'BE',
    'cz': 'CZ',
    'hu': 'HU',
    'ro': 'RO',
    'bg': 'BG',
    'gr': 'GR',
    'it': 'IT',
    'es': 'ES',
    'pt': 'PT',
    'gb': 'GB',
    'uk': 'GB',
    'ie': 'IE',
    'lv': 'LV',
    'lt': 'LT',
    'sk': 'SK',
    'si': 'SI',
    'hr': 'HR',
    'rs': 'RS',
    'md': 'MD',
    'ua': 'UA',
    'by': 'BY',
    'kz': 'KZ',
    'tr': 'TR',
    'il': 'IL',
    'ae': 'AE',
    'cn': 'CN',
    'jp': 'JP',
    'kr': 'KR',
    'sg': 'SG',
    'hk': 'HK',
    'tw': 'TW',
    'au': 'AU',
    'nz': 'NZ',
    'ca': 'CA',
    'us': 'US',
    'br': 'BR',
    'ar': 'AR',
    'mx': 'MX',
    'cl': 'CL',
    'co': 'CO',
    'pe': 'PE',
    'za': 'ZA',
    'ng': 'NG',
    'eg': 'EG',
    'th': 'TH',
    'vn': 'VN',
    'my': 'MY',
    'pk': 'PK',
    'ir': 'IR',
    'iq': 'IQ',
    'sa': 'SA',
    'qa': 'QA',
    'kw': 'KW',
    'est': 'EE',
    'nld': 'NL',
    'deu': 'DE',
    'rus': 'RU',
    'fra': 'FR',
    'pol': 'PL',
    'swe': 'SE',
    'nor': 'NO',
    'dnk': 'DK',
    'aut': 'AT',
    'che': 'CH',
    'bel': 'BE',
    'cze': 'CZ',
    'hun': 'HU',
    'rou': 'RO',
    'bgr': 'BG',
    'grc': 'GR',
    'ita': 'IT',
    'esp': 'ES',
    'prt': 'PT',
    'gbr': 'GB',
    'irl': 'IE',
    'isl': 'IS',
    'lva': 'LV',
    'ltu': 'LT',
    'svk': 'SK',
    'svn': 'SI',
    'hrv': 'HR',
    'srb': 'RS',
    'mda': 'MD',
    'ukr': 'UA',
    'blr': 'BY',
    'kaz': 'KZ',
    'tur': 'TR',
    'isr': 'IL',
    'are': 'AE',
    'ind': 'IN',
    'chn': 'CN',
    'jpn': 'JP',
    'kor': 'KR',
    'sgp': 'SG',
    'hkg': 'HK',
    'twn': 'TW',
    'aus': 'AU',
    'nzl': 'NZ',
    'can': 'CA',
    'bra': 'BR',
    'arg': 'AR',
    'mex': 'MX',
    'chl': 'CL',
    'col': 'CO',
    'per': 'PE',
    'zaf': 'ZA',
    'nga': 'NG',
    'egy': 'EG',
    'tha': 'TH',
    'vnm': 'VN',
    'idn': 'ID',
    'mys': 'MY',
    'pak': 'PK',
    'irn': 'IR',
    'irq': 'IQ',
    'sau': 'SA',
    'qat': 'QA',
    'kwt': 'KW',
  };

  /// Флажок сервера: сначала настоящий флаг-эмодзи из имени (любого вида —
  /// см. [ServerFlag]), и только если его нет — догадка по названию страны.
  static ServerFlag? extractFlag(String displayName) {
    if (displayName.isEmpty) return null;
    final emoji = firstFlagIn(displayName);
    if (emoji != null) return emoji;
    final code = _countryCodeFromKeywords(displayName);
    return code == null ? null : FlagArt(code.toLowerCase());
  }

  /// ISO alpha-2 код региона сервера, если у его флажка такой код есть.
  static String? extractCountryCode(String displayName) =>
      switch (extractFlag(displayName)) {
        FlagArt(:final countryCode) => countryCode,
        _ => null,
      };

  static String? _countryCodeFromKeywords(String displayName) {
    final lower = displayName.toLowerCase();

    // Многословные названия ("hong kong", "united states", "южная африка")
    // достаточно уникальны, чтобы безопасно искать их как подстроку.
    for (final entry in _keywords.entries) {
      if (entry.key.contains(' ') && lower.contains(entry.key)) {
        return entry.value;
      }
    }

    // Одиночные названия и 2–3-буквенные коды матчим только как целое слово.
    // Раньше здесь был поиск подстроки по всем ключам, из-за чего произвольные
    // имена без страны получали чужой флаг: "cloudflare" → "are" (ARE=ОАЭ),
    // "southampton" → "pt" (PT), "united kingdom" → "ng" (NG) и т.п.
    final tokens = lower
        .replaceAll(RegExp(r'[|,\-_/\\]'), ' ')
        .split(RegExp(r'\s+'))
        .map((s) => s.replaceAll(RegExp(r'[^a-zа-яё]'), ''))
        .where((s) => s.isNotEmpty);

    for (final tok in tokens) {
      final code = _keywords[tok];
      if (code != null) return code;
    }

    return null;
  }

  static String cleanDisplayName(String displayName) {
    final cleaned = stripFlags(displayName).trim();
    final match = RegExp(r'^[A-Z]{2}\s+(.+)$').firstMatch(cleaned);
    return match != null ? match.group(1)!.trim() : cleaned;
  }

  static String formatForDisplay(String displayName, {int maxLength = 30}) {
    final cleaned = cleanDisplayName(displayName);
    if (cleaned.length <= maxLength) return cleaned;
    return '${cleaned.substring(0, maxLength - 3)}...';
  }
}
